### PR TITLE
Fix build error on Linux 6.11: update virtio_find_vqs() to use virtqueue_info

### LINKED ISSUE #73: Failed to build with Linux v6.11
Reported by CI, on a Linux v6.11 host:
```
make -C /lib/modules/6.11.0-1012-azure/build M=/home/runner/work/vwifi/vwifi modules
  cc -std=gnu99 -Wno-declaration-after-statement -o vwifi-tool vwifi-tool.c
  make[1]: Entering directory '/usr/src/linux-headers-6.11.0-1012-azure'
  warning: the compiler differs from the one used to build the kernel
    The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
    You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
    CC [M]  /home/runner/work/vwifi/vwifi/vwifi.o
  /home/runner/work/vwifi/vwifi/vwifi.c: In function ‘vwifi_virtio_init_vqs’:
  /home/runner/work/vwifi/vwifi/vwifi.c:3170:60: error: passing argument 4 of ‘virtio_find_vqs’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   3170 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, callbacks, names,
        |                                                            ^~~~~~~~~
        |                                                            |
        |                                                            void (**)(struct virtqueue *)
  In file included from /home/runner/work/vwifi/vwifi/vwifi.c:11:
  ./include/linux/virtio_config.h:223:43: note: expected ‘struct virtqueue_info *’ but argument is of type ‘void (**)(struct virtqueue *)’
    223 |                     struct virtqueue_info vqs_info[],
        |                     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  /home/runner/work/vwifi/vwifi/vwifi.c:3170:71: error: passing argument 5 of ‘virtio_find_vqs’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   3170 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, callbacks, names,
        |                                                                       ^~~~~
        |                                                                       |
        |                                                                       const char **
  ./include/linux/virtio_config.h:224:42: note: expected ‘struct irq_affinity *’ but argument is of type ‘const char **’
    224 |                     struct irq_affinity *desc)
        |                     ~~~~~~~~~~~~~~~~~~~~~^~~~
  /home/runner/work/vwifi/vwifi/vwifi.c:3170:12: error: too many arguments to function ‘virtio_find_vqs’
   3170 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, callbacks, names,
        |            ^~~~~~~~~~~~~~~
  ./include/linux/virtio_config.h:221:5: note: declared here
    221 | int virtio_find_vqs(struct virtio_device *vdev, unsigned int nvqs,
        |     ^~~~~~~~~~~~~~~
  cc1: some warnings being treated as errors
  make[3]: *** [scripts/Makefile.build:244: /home/runner/work/vwifi/vwifi/vwifi.o] Error 1
  make[2]: *** [/usr/src/linux-headers-6.11.0-[101](https://github.com/sysprog21/vwifi/actions/runs/14741735868/job/41392812159#step:4:102)2-azure/Makefile:1932: /home/runner/work/vwifi/vwifi] Error 2
  make[1]: *** [Makefile:224: __sub-make] Error 2
  make[1]: Leaving directory '/usr/src/linux-headers-6.11.0-1012-azure'
  make: *** [Makefile:11: kmod] Error 2
  cpp/autobuilder: trying to run make [current dir: /home/runner/work/vwifi/vwifi]
  make -C /lib/modules/6.11.0-1012-azure/build M=/home/runner/work/vwifi/vwifi modules
  make[1]: Entering directory '/usr/src/linux-headers-6.11.0-1012-azure'
  warning: the compiler differs from the one used to build the kernel
    The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
    You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
    CC [M]  /home/runner/work/vwifi/vwifi/vwifi.o
  /home/runner/work/vwifi/vwifi/vwifi.c: In function ‘vwifi_virtio_init_vqs’:
  /home/runner/work/vwifi/vwifi/vwifi.c:3170:60: error: passing argument 4 of ‘virtio_find_vqs’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   3170 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, callbacks, names,
        |                                                            ^~~~~~~~~
        |                                                            |
        |                                                            void (**)(struct virtqueue *)
  In file included from /home/runner/work/vwifi/vwifi/vwifi.c:11:
  ./include/linux/virtio_config.h:223:43: note: expected ‘struct virtqueue_info *’ but argument is of type ‘void (**)(struct virtqueue *)’
    223 |                     struct virtqueue_info vqs_info[],
        |                     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  /home/runner/work/vwifi/vwifi/vwifi.c:3170:71: error: passing argument 5 of ‘virtio_find_vqs’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   3170 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, callbacks, names,
        |                                                                       ^~~~~
        |                                                                       |
        |                                                                       const char **
  ./include/linux/virtio_config.h:224:42: note: expected ‘struct irq_affinity *’ but argument is of type ‘const char **’
    224 |                     struct irq_affinity *desc)
        |                     ~~~~~~~~~~~~~~~~~~~~~^~~~
  /home/runner/work/vwifi/vwifi/vwifi.c:3170:12: error: too many arguments to function ‘virtio_find_vqs’
   3170 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, callbacks, names,
        |            ^~~~~~~~~~~~~~~
  ./include/linux/virtio_config.h:221:5: note: declared here
    221 | int virtio_find_vqs(struct virtio_device *vdev, unsigned int nvqs,
        |     ^~~~~~~~~~~~~~~
  cc1: some warnings being treated as errors
  make[3]: *** [scripts/Makefile.build:244: /home/runner/work/vwifi/vwifi/vwifi.o] Error 1
```

### PR DESCRIPTION
**Pull request by horseface1110**
This patch updates the call to `virtio_find_vqs()` to follow the new signature introduced in Linux 6.11, which replaces the separate `callbacks` and `names` arrays with a `struct virtqueue_info[]`.

Tested on:
- Kernel: 6.11.0
- Distro: Ubuntu 24.04
- Confirmed `vwifi.ko` builds and loads successfully

This resolves #73.

### CODE REVIEW

**Comment by horseface1110** [comment]
result：
```
oloomb@oloomb:~/vwifi$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether bc:24:11:36:19:75 brd ff:ff:ff:ff:ff:ff
    altname enp0s18
3: vw0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:76:77:30:00:00 brd ff:ff:ff:ff:ff:ff
4: vw1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:76:77:31:00:00 brd ff:ff:ff:ff:ff:ff
5: vw2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:76:77:32:00:00 brd ff:ff:ff:ff:ff:ff
6: vw3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:76:77:33:00:00 brd ff:ff:ff:ff:ff:ff
7: vw4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:76:77:34:00:00 brd ff:ff:ff:ff:ff:ff
```

**Comment by jserv** [comment]
The proposed change breaks the build on Linux v6.8:
```
/tmp/vwifi/vwifi.c: In function ‘vwifi_virtio_init_vqs’:
/tmp/vwifi/vwifi.c:3170:27: error: array type has incomplete element type ‘struct virtqueue_info’
 3170 |     struct virtqueue_info vqs_info[VWIFI_NUM_VQS];
      |                           ^~~~~~~~
/tmp/vwifi/vwifi.c:3177:12: error: too few arguments to function ‘virtio_find_vqs’
 3177 |     return virtio_find_vqs(vdev, VWIFI_NUM_VQS, vwifi_vqs, vqs_info, NULL);
      |            ^~~~~~~~~~~~~~~
In file included from /tmp/vwifi/vwifi.c:11:
./include/linux/virtio_config.h:228:5: note: declared here
  228 | int virtio_find_vqs(struct virtio_device *vdev, unsigned nvqs,
      |     ^~~~~~~~~~~~~~~
/tmp/vwifi/vwifi.c:3170:27: warning: unused variable ‘vqs_info’ [-Wunused-variable]
 3170 |     struct virtqueue_info vqs_info[VWIFI_NUM_VQS];
      |                           ^~~~~~~~
/tmp/vwifi/vwifi.c:3178:1: error: control reaches end of non-void function [-Werror=return-type]
 3178 | }
      | ^
cc1: some warnings being treated as errors
```

You must ensure the changes are compatible with older Linux versions.

File: vwifi.c [hunk 1]
```diff
@@ -17,6 +17,7 @@
 #include <linux/netlink.h>
 #include <net/sock.h>
 
+
```
Comment (jserv) [inline vwifi.c:20]: Don't do this. Minimize the necessary changes.

**Review by jserv — CHANGES_REQUESTED** [review]
You should check the git history of the Linux kernel to locate the exact commit hash that indicates the interface changes to `virtio_find_vqs()`, so that the commit messages can be more informative.

Example: https://github.com/sysprog21/simplefs/commit/357a813a1d504624495a76a94469aadc9c434120

**Review by jychen0611 — CHANGES_REQUESTED** [review]
Refine the assignment of `ctx`. It is a bool, so avoid using `NULL`. Use `true` or `false` depending on whether extra context is required.

**Review by jserv — CHANGES_REQUESTED** [review]
Use `git rebase -i` to squash and rework commits. Then, append `Close #73` at the end of git commit messages.

**Comment by horseface1110** [comment]
> Have you tested the virtio-related feature after your modification?

Thanks for the reminder. I initially thought it worked and closed #73, but after rechecking, I found the virtio feature still has issues. I’ll reopen the issue and follow up with a fix soon.

**Comment by horseface1110** [comment]
This PR addresses API changes introduced in Linux kernel v6.11.

During the process, I also noticed additional modifications required for compatibility with v6.15.
I will open a new PR specifically for handling the v6.15-related updates to keep the changes clean and focused.

Please let me know if anything else needs to be adjusted here. Thank you!

**Review by jychen0611 — APPROVED** [review]

**Review by jychen0611 — CHANGES_REQUESTED** [review]
Avoid using backticks ( ` ) in commit subjects. Backticks can be easily confused with single quotes on some terminals, reducing readability. Plain text or single quotes provide sufficient clarity and emphasis.

**Comment by jserv** [comment]
> During the process, I also noticed additional modifications required for compatibility with v6.15. I will open a new PR specifically for handling the v6.15-related updates to keep the changes clean and focused.

Create a new issue to address v6.15 compatibility. Let's concentrate on Linux v6.11 here.

**Review by jserv — CHANGES_REQUESTED** [review]
Consider the following git commit messages:
```
Support Linux v6.11

Update virtqueue setup to use the new virtio_find_vqs() interface
introduced in Linux commit c502eb8 ("virtio: Introduce struct
virtqueue_info and find_vqs_info() config op"), which now takes an array
of struct virtqueue_info instead of separate parameter arrays.

The legacy virtio_find_vqs() interface was replaced in Linux commit
6c85d6b ("virtio: Rename virtio_find_vqs_info() to virtio_find_vqs")
with a new implementation using struct virtqueue_info.

Since the original code relied on virtio_find_vqs() with implicit NULL
context, the ctx field is set to false to maintain equivalent behavior. 
```

**Comment by jserv** [comment]
Thank @horseface1110 for contributing!
